version: '3.8'

services:
  financial-analyzer:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

networks:
  default:
    driver: bridge
